(define-abbrev-table 'global-abbrev-table '(
                                            ("alpha" "α")
                                            ("inf" "∞")
                                            ("ar" "→")
                                            (" s." " § ")
                                            (" sec. " " § ")
                                            (" usc " " U.S.C. ")
                                            ("ccp" "Cal. Code Civ. Proc. § ")
                                            (" ca3" " Cal. App. 3d ")
                                            (" ca4" " Cal. App. 4th ")
                                            (" ca5" " Cal. App. 5th ")
                                            (" Cal. 2d" " Cal. 2d ")
                                            (" Cal. 3d" " Cal. 3d ")
                                            (" Cal. 4" " Cal. 4thd ")
                                            (" Cal. 5" " Cal. 5th ")
                                            ("hhe" "rmccarl@hueston.com")
                                            ("--" "–")
                                            ("---" "—")
                                            ))
